### ISSUE TITLE
这个是啥呀

### ISSUE THREAD

**Issue by xivi1839** [ingbyr/VDM#83]
2019-04-15 03:38:36.104 [JavaFX Application Thread] DEBUG com.ingbyr.vdm.Main.<init>(26) - OS: Windows 10 Arch: amd64 Version: 10.0
2019-04-15 03:38:36.113 [JavaFX Application Thread] DEBUG com.ingbyr.vdm.Main.<init>(27) - JAVA: 1.8.0_172 Vender: Oracle Corporation
2019-04-15 03:38:36.114 [JavaFX Application Thread] DEBUG com.ingbyr.vdm.Main.<init>(28) - Default Locale: zh_CN Current Locale:zh_CN
2019-04-15 03:38:36.114 [JavaFX Application Thread] DEBUG com.ingbyr.vdm.Main.<init>(29) - Save config file to C:\Users\Administrator\.vdm\vdm.properties

==========================

![Snipaste_2019-04-15_02-45-43](https://user-images.githubusercontent.com/24610024/56098198-a6062400-5f30-11e9-8653-c70434887b62.png)

**Comment by xivi1839** [comment]
org.mapdb.DBException$FileLocked: File is already opened and is locked: C:\Users\Administrator\.vdm\vdm.db
	at org.mapdb.volume.Volume.lockFile(Volume.java:502)
	at org.mapdb.volume.RandomAccessFileVol.<init>(RandomAccessFileVol.java:52)
	at org.mapdb.volume.RandomAccessFileVol$1.makeVolume(RandomAccessFileVol.java:26)
	at org.mapdb.StoreWAL$realVolume$1.invoke(StoreWAL.kt:75)
	at org.mapdb.StoreWAL$realVolume$1.invoke(StoreWAL.kt:18)
	at org.mapdb.StoreWAL.<init>(StoreWAL.kt:74)
	at org.mapdb.StoreWAL$Companion.make(StoreWAL.kt:56)
	at org.mapdb.StoreWAL$Companion.make$default(StoreWAL.kt:55)
	at org.mapdb.DBMaker$Maker.make(DBMaker.kt:464)
	at com.ingbyr.vdm.controllers.MainController.<init>(MainController.kt:28)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at tornadofx.FXKt.find(FX.kt:402)
	at com.ingbyr.vdm.views.MainView$$special$$inlined$inject$1.getValue(Component.kt:1135)
	at com.ingbyr.vdm.views.MainView$$special$$inlined$inject$1.getValue(Component.kt:173)
	at com.ingbyr.vdm.views.MainView.getController(MainView.kt)
	at com.ingbyr.vdm.views.MainView.<init>(MainView.kt:60)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at tornadofx.FXKt.find(FX.kt:402)
	at tornadofx.FXKt.find$default(FX.kt:388)
	at tornadofx.App.start(App.kt:78)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$161(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$174(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Thread.java:748)

**Comment by xivi1839** [comment]
VDM 0.3.1版本
电脑系统操作：微软 1809最新版本

**Comment by ingbyr** [comment]
是不是之前强退过应用？删除数据库文件`C:\Users\Administrator.vdm\vdm.db`可以解决

**Comment by xivi1839** [comment]
java.io.IOException: Cannot run program "D:\VDM\VDM\app\package\windows\engine\youtube-dl.exe": CreateProcess error=193, %1 不是有效的 Win32 应用程序。
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.ingbyr.vdm.engine.YoutubeDL.execCommand(YoutubeDL.kt:206)
	at com.ingbyr.vdm.engine.YoutubeDL.downloadMedia(YoutubeDL.kt:165)
	at com.ingbyr.vdm.controllers.MainController$startTask$1.invoke(MainController.kt:75)
	at com.ingbyr.vdm.controllers.MainController$startTask$1.invoke(MainController.kt:21)
	at tornadofx.FXTask.call(Async.kt:437)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: CreateProcess error=193, %1 不是有效的 Win32 应用程序。
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 10 more

**Comment by xivi1839** [comment]
提示这个
